### ISSUE TITLE
Problem with simulate_data when trying to reproduce the provided example

### ISSUE THREAD

**Issue by lucasmiranda42** [blind-contours/SuperNOVA#2]
Hello again!  Another issue from [5422](https://github.com/openjournals/joss-reviews/issues/5422) here.

I run into a problem when trying to run the provided example. Upon excecuting

`simulate_data(n_obs = n_obs, shift_var_index = c(3))`

I get an error:

`Error in simulate_data(n_obs = n_obs, shift_var_index = c(3)) : 
  unused argument (shift_var_index = c(3))`

Since the parameter `shift_var_index` does not seem to be part of the API anymore. Please clarify or update the documentation.

Best!
Lucas

**Comment by blind-contours** [comment]
Hi @lucasmiranda42 - thanks for your review of the package. I've since updated this function and improved documentation in the README. Now I just build in the shift index and in the README I show correct estimation for each parameter.

**Comment by lucasmiranda42** [comment]
Wonderful! I'll close and reopen if needed
