### ISSUE TITLE
Failed to install 'SuperNOVA' from Github.

### ISSUE THREAD

**Issue by hasdk** [blind-contours/SuperNOVA#5]
Hello,

I am trying to install SuperNOVA on a windows 10 machine with R version 4.3.2.
I successfully installed `sl3` and the other packages; however, when I run

 `remotes::install_github("blind-contours/SuperNOVA@main")`

I get the following error:

```
-- R CMD build ----------------------------------------------------------------------------------------
v  checking for file 'C:\Users\saddih01\AppData\Local\Temp\RtmpmQfME9\remotes2f5c7fe66900\blind-contours-SuperNOVA-a92544e/DESCRIPTION' ... OK
-  preparing 'SuperNOVA': (2s)
E  checking DESCRIPTION meta-information ... 
   Malformed package version.
   
   See section 'The DESCRIPTION file' in the 'Writing R Extensions'
   manual.
Error: Failed to install 'SuperNOVA' from GitHub:
  ! System command 'Rcmd.exe' failed 
```

Thank you in advance for your assistance with this issue.

**Comment by blind-contours** [comment]
Hi hasdk, 

I am decommissioning this package in favor of better methods for identifying and estimating interaction and effect modification in mixed exposures. 

For interaction please use: 

https://github.com/blind-contours/InterXshift

For effect modification please use: 

https://github.com/blind-contours/EffectXshift

These should install with no errors but if you do have any issues please reach out on the issues pages there. 

Let me know if you have any other questions.

**Comment by hasdk** [comment]
I will checkout the suggested packages. Thank you !
